### ISSUE TITLE
This dosnt have a index.js so spicetify is not letting me load it

### ISSUE THREAD

**Issue by swayz8148** [Pithaya/spicetify-apps-dist#1]
spicetify\CustomApps
![image](https://user-images.githubusercontent.com/113429324/221011403-f048062d-c147-4678-a2f7-e52f2bdfa9b0.png)
spicetify\CustomApps\eternal-jukebox
![image](https://user-images.githubusercontent.com/113429324/221011251-48ecfeb2-ba07-4063-b651-ca68aa19ca57.png)

The error I'm getting
![image](https://user-images.githubusercontent.com/113429324/221011182-4ce01d50-861f-491e-9b98-ae773f147091.png)

When I go on the app I get
![image](https://user-images.githubusercontent.com/113429324/221012800-f40e449e-508f-44ae-85c6-48735dfb77f1.png)

**Comment by Pithaya** [comment]
My bad, I forgot to add the installation steps in the readme...
The main branch only has the source files, to get the index.js file and others you need to switch to the `dist/eternal-jukebox` branch:
![image](https://user-images.githubusercontent.com/19533412/221037257-2e7ec827-09bb-49cc-b482-7310d768770a.png)

**Comment by swayz8148** [comment]
alright thank you for responding I cant wait to test this out
everything is working now thanks
