### ISSUE TITLE
Uninstall better local files

### ISSUE THREAD

**Issue by Grxffiti** [Pithaya/spicetify-apps-dist#11]
Hey I installed it and removed the copied files to remove it but it won't go away, how do I uninstall it? btw uninstalling because it merges albums with the same name into one even from diff artists

**Comment by Pithaya** [comment]
To uninstall it completely you also need to run the following commands:
```
spicetify config custom_apps better-local-files-
spicetify apply
```

As for the albums being merged, I think I'll have a fix ready soon, I can ping this issue when it's done if you're interested.

**Comment by Grxffiti** [comment]
thanks dude sure let me know

**Comment by Pithaya** [comment]
Both issues should be fixed now, for the merged albums you'll need to follow the steps in the readme (basically just go to the top right menu while in the custom app -> rebuild local album cache).
You can reopen this issue if the merge fix is not working.
