### ISSUE TITLE
Could you make font parity with local files and songs on playlists?

### ISSUE THREAD

**Issue by ShiestGuy** [Pithaya/spicetify-apps-dist#16]
im not sure if this is really necessary, but it gets on my nerves how the font for local file songs are different than regular spotify songs when on playlists. like, the font for the album title is larger and a little bit bolder, and the artist name seems to be a little transparent. any chance you could fix this, perhaps as an optional change in the better local files app?

**Comment by Pithaya** [comment]
Can you post a screenshot ? I'm not sure I see where the issue is

**Comment by ShiestGuy** [comment]
![differenef](https://user-images.githubusercontent.com/51003621/232229318-9d95fae7-0d21-43ff-a094-fc187d2c34a4.png)
see the differences between text? significantly album name

**Comment by Pithaya** [comment]
I see, it's a theme issue then, the fonts are the same for some themes (like the default and sleek) but there is this issue for some others (dreary for exemple), so you'll have to link this issue / create a new one in the repo of the theme you're using

**Comment by ShiestGuy** [comment]
ok thank you
