### ISSUE TITLE
Doesn't seem to be working.

### ISSUE THREAD

**Issue by iamMG** [Pithaya/spicetify-apps-dist#18]
Jukebox doesn't seem to be working. Current song doesn't automatically loop. Have to manually 'enable Repeat one'. Still jukebox not doing anything imo. No branching visible.
Spotify for Windows: 1.2.9.743.g85d9593d
Spicetify: v2.17.2

**Comment by Pithaya** [comment]
What do you see on the custom app's page ? Is there a graph ?

**Comment by iamMG** [comment]
Yes there's a graph. But no infinite playback.
![image](https://user-images.githubusercontent.com/22472867/232307909-feeee3dc-6ed6-43c2-aed9-c979e5690ade.png)

**Comment by Pithaya** [comment]
Seems like the default settings don't really work for this particular song, if you increase the branch similarity threshold they will generate. The quality of the skips will decrease a bit though.
