### ISSUE TITLE
how to get album covers to work?

### ISSUE THREAD

**Issue by ShiestGuy** [Pithaya/spicetify-apps-dist#19]
I think this is awesome, but I cannot for the life of me get album covers to appear. I tried using an image in the folder, it doesn't work. I also gave all the mp3s album art, but that didn't work either. What do I do?

**Comment by Pithaya** [comment]
I guess you mean that you get this icon instead of album covers right ?  

![image](https://user-images.githubusercontent.com/19533412/232229377-b6c181dd-1898-41ff-90ab-92bf704fc277.png)

Are the covers also missing in the default spotify local files page ?

**Comment by ShiestGuy** [comment]
both yes. whats odd is that it works for "Il Etait Une Foret" but not this one.
![image](https://user-images.githubusercontent.com/51003621/232229761-1ae574ad-03a1-4221-8e93-0604c7de19ae.png)

**Comment by ShiestGuy** [comment]
and when I open the songs in apps like windows media player and VLC it shows me that the album has a cover

**Comment by Pithaya** [comment]
If the original view does not have covers as well it's probably that spotify didn't refresh its cache, try changing the name of the folder where you have your files, it should force the files data to refresh

**Comment by ShiestGuy** [comment]
still didn't work. Whats odd is that my spicetify theme, one that changes the color of text to match the album art, is working, as all the text is becoming blue. However, the album art is still not showing. Cleared cache, renamed folder, cant really think of anything else.
![untitled](https://user-images.githubusercontent.com/51003621/232254056-abbed7a7-a428-4cec-99df-493f672e6ce8.jpg)
here's the album art I'm going for.
![image](https://user-images.githubusercontent.com/51003621/232254085-2fb21ec2-428e-439c-a169-77e50d0fc407.png)
this is what my screen looks like while listening to one of the songs

**Comment by ShiestGuy** [comment]
I got it to work using a program called mp3tag! The way spotify processes this stuff is seemingly weird af, but finally it works!
