### ISSUE TITLE
eternal jukebox says its not enabled how do i fix that

### ISSUE THREAD

**Issue by v4lentine1** [Pithaya/spicetify-apps-dist#2]

**Comment by Pithaya** [comment]
Did you click on the button that's on the play bar to enable it ?

![image](https://user-images.githubusercontent.com/19533412/222229032-83f0b310-326c-4fbf-8a9b-9a4992fc9d71.png)

**Comment by v4lentine1** [comment]
it doesnt show that. 
![image](https://user-images.githubusercontent.com/126353073/222729255-cd0a38b0-123e-43ee-8c75-a2cfcc1245b1.png)

**Comment by jcav2212** [comment]
I have the same problem however mine shows the loop button and when clicking it still says jukebox not enabled.

**Comment by Pithaya** [comment]
> it doesnt show that. ![image](https://user-images.githubusercontent.com/126353073/222729255-cd0a38b0-123e-43ee-8c75-a2cfcc1245b1.png)

There's probably a bug in the extension then, the custom app's link in the side bar is correctly displayed right ? Can you tell me what other extensions / custom apps you have installed ? Maybe there's a conflict somewhere.

> I have the same problem however mine shows the loop button and when clicking it still says jukebox not enabled. Was I supposed to download the zip or do something else?

If you can see the loop button then I guess it's installed correctly. Is it nor working only for a few songs or all of them ?

**Comment by v4lentine1** [comment]
> 
i have a lot of extensions  installed.
![image](https://user-images.githubusercontent.com/126353073/222913309-de3103ea-0ef6-4651-8095-96ac120e3445.png)
![image](https://user-images.githubusercontent.com/126353073/222913312-14bfa0f0-13da-4d68-bffa-7fbfa95cbabe.png)
the ones with the red outline are the ones that are installed.

**Comment by jcav2212** [comment]
> If you can see the loop button then I guess it's installed correctly. Is it not working only for a few songs or all of them ?

I don't think it's working on any. I have the loop icon next to play/pause enabled but I don't see anything happening. When I click on the Eternal Jukebox tab on the side it just says Jukebox not enabled.

**Comment by Pithaya** [comment]
> i have a lot of extensions installed.

I tried with the same extensions and theme and it works fine, so it's probably not a conflict issue...

Can you both install the latest version of the app and try again, see if there are any error messages appearing ? There was an issue with error notifications not being triggered correctly, it should be fixed now.

**Comment by v4lentine1** [comment]
ill try and let you know

**Comment by jcav2212** [comment]
I tried deleting the files and redownloading but it doesn't seem like anything changed. After clicking on the infinity button it just says "Fetching analysis for song..."

**Comment by KawaiiiSheep** [comment]
have the same issue here no fix for it found and no song seems to change it

**Comment by ShadowG0D** [comment]
I'm also having this issue, nothing installed but whatever is default for spicetify

**Comment by ShadowG0D** [comment]
additionally though, it's throwing the following error message:
``spicetify v2.16.2
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error Custom app "eternal-jukebox" not found.
OK
Transferring custom apps:
error Custom app "eternal-jukebox" not found.
OK
success Spotify is spiced up!``

**Comment by jcav2212** [comment]
Damn it just works now :)

**Comment by Pithaya** [comment]
> additionally though, it's throwing the following error message when i run spicetify apply: `spicetify v2.16.2 Overwriting themed assets: OK Transferring user.css: OK Applying additional modifications: error Custom app "eternal-jukebox" not found. OK Transferring custom apps: error Custom app "eternal-jukebox" not found. OK success Spotify is spiced up!`

I think custom apps should be in the AppData/Roaming folder instead of AppData/Local, maybe it's expecting the folder to be there ?
What do you get when you run `spicetify -a path` and `spicetify -c` ?

**Comment by ShadowG0D** [comment]
C:\Users\%username%> spicetify -a path
C:\Users\%username%\AppData\Roaming\spicetify\CustomApps\marketplace
C:\Users\%username%\AppData\Roaming\spicetify\CustomApps\eternal-jukebox
spicetify -c:
C:\Users\talen\AppData\Roaming\spicetify\config-xpui.ini

**Comment by ShadowG0D** [comment]
PS C:\Users\%username%> spicetify config custom_apps eternal-jukebox
warning Config "custom_apps" unchanged: eternal-jukebox is already in the list.

**Comment by Pithaya** [comment]
@ShadowG0D Seems like the app is correctly added to the config so maybe check that the folder in `C:\Users\%username%\AppData\Roaming\spicetify\CustomApps\eternal-jukebox` exists and has the correct files ?

@v4lentine1 Finally found the bug for the missing playbar button, it should be good in the latest version
