### ISSUE TITLE
Getting stuck on same branch

### ISSUE THREAD

**Issue by BurnElmo** [Pithaya/spicetify-apps-dist#24]
On some songs, when I enable the eternal jukebox, it repeats the same branch for infinity, even after I lowered the branch chance.

**Comment by Pithaya** [comment]
Maybe there are no other branches in the path to the branch that always repeat, can you give me an example of a song with the issue and your jukebox settings ?

**Comment by BurnElmo** [comment]
It stopped happening after I updated spicetify, my settings were probably showing incorrectly.
