### ISSUE TITLE
Better Local Files "Something went wrong"

### ISSUE THREAD

**Issue by Ochomama1** [Pithaya/spicetify-apps-dist#25]
I downloaded every file for Better Local Files, but it doesn't appear to be working. When I click the local files tab I get the "Something went wrong" screen.

**Comment by Pithaya** [comment]
Did you download every file individually ? Try to delete every files in your `better-local-files` folder, download the app as a zip archive from [here](https://github.com/Pithaya/spicetify-apps-dist/archive/refs/heads/dist/better-local-files.zip), extract it, and then put the files from the archive into your empty `better-local-files` folder.

**Comment by Ochomama1** [comment]
Just did that, still seeing the "Something went wrong" screen

**Comment by Ochomama1** [comment]
Any update on this?

**Comment by Pithaya** [comment]
Can you try to see if it works with the latest version of the custom app ? I fixed some bugs recently, maybe one of them was causing the issue

**Comment by Ochomama1** [comment]
Still not working

**Comment by Ochomama1** [comment]
I reinstalled spicetify due to another issue and it works now.
