### ISSUE TITLE
Every time I install a new mod for Spicetify, the other mods are installed again, and new buttons are created that I don't need.

### ISSUE THREAD

**Issue by plasmateo** [Pithaya/spicetify-apps-dist#28]
How I solve that? 
![grafik](https://github.com/Pithaya/spicetify-apps-dist/assets/138035215/d16570bc-983f-486b-8a0a-6b9d25082238)

**Comment by Vibecat111** [comment]
try running 'spicetify config-dir' in pw and then click on the config-xpui.ini, and try removing the duplicates in custom_apps
