### ISSUE TITLE
Completly broken, Eternal Jukebox

### ISSUE THREAD

**Issue by Tr3yWay996** [Pithaya/spicetify-apps-dist#33]
Absolutly nothing work, every time i install it, well nothing happen, *an error ocured* , tf

**Comment by DannyLeWasTaken** [comment]
I can confirm it is broken for me too. When clicking on the eternal jukebox icon, it breaks completely

**Comment by JoukoG** [comment]
Same!

**Comment by Pithaya** [comment]
One of the latest Spotify updates broke some stuff, if you install the latest version of the custom app it should work again now.
