### ISSUE TITLE
Jukebox not enable

### ISSUE THREAD

**Issue by MagicCoto** [Pithaya/spicetify-apps-dist#38]
I just downloaded the latest .zip and installed the app, but when I go into Spotify and go into Eternal Jukebox it says not enable.
![image](https://github.com/Pithaya/spicetify-apps-dist/assets/78121694/6526cd5b-6a63-4ea0-a3cc-489bff1cd6dd)
![image](https://github.com/Pithaya/spicetify-apps-dist/assets/78121694/12a9ad88-b0af-483d-9bcd-55319859cda3)
How can i enable it?

**Comment by MagicCoto** [comment]
Bro

**Comment by MagicCoto** [comment]
I'm an idiot, cheers

**Comment by Demon-X14** [comment]
> I'm an idiot, cheers

How did you fix ?
