### ISSUE TITLE
No analysis available for this track

### ISSUE THREAD

**Issue by aiidddxn** [Pithaya/spicetify-apps-dist#43]
Can't enable eternal jukebox

**Comment by marcoderso** [comment]
Same here, suddenly there are no analysis avaliable anymore for any song.

**Comment by aiidddxn** [comment]
An unconvenient workaround is to downgrade to 1.2.30.1135, but get ready for spotify to update itself

**Comment by marcoderso** [comment]
> 1.2.30.1135

Maybe a dumb question, but how does one downgrade to this version?
