### ISSUE TITLE
Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by prodbyeagle** [Pithaya/spicetify-apps-dist#45]
![image](https://github.com/Pithaya/spicetify-apps-dist/assets/124641014/13baddde-fd6f-47ed-a9af-c9e6da1d6d92)

i get this error

**Comment by bruhkidd0** [comment]
me too bruh idk what that means

**Comment by Edgezer** [comment]
Same problem here

**Comment by prodbyeagle** [comment]
it the source code anywhere avalible? i want to look at it and maybe fix it my self

**Comment by spliitbtw** [comment]
1 week and its not fixed

**Comment by BlackusPL** [comment]
> it the source code anywhere avalible? i want to look at it and maybe fix it my self

There
https://github.com/Pithaya/spicetify-apps
