### ISSUE TITLE
BetterLocalFiles crashes at songlist 

### ISSUE THREAD

**Issue by sonat1ne** [Pithaya/spicetify-apps-dist#48]
When opening local files, Spotify is forced to reload.
![Screenshot 2024-03-29 192710](https://github.com/Pithaya/spicetify-apps-dist/assets/138820650/95a35022-ed58-4e8b-95a8-e7e4329343e2)
Granted, I have a lot of local files, so this might be part of the issue.
![Screenshot 2024-03-29 192829](https://github.com/Pithaya/spicetify-apps-dist/assets/138820650/276cecb7-70e7-4035-888d-758f4b53d8d9)
However, I can still access the other pages (albums & artists) if I click into them fast enough before Spotify reloads.
![Screenshot 2024-03-29 192743](https://github.com/Pithaya/spicetify-apps-dist/assets/138820650/19c66cb2-35f7-45aa-80f7-9fdfd89c4ea6)
![Screenshot 2024-03-29 192732](https://github.com/Pithaya/spicetify-apps-dist/assets/138820650/3ba81d3a-cb62-4e3e-9a9b-01649cf9682e)

**Comment by znicuuu** [comment]
![image](https://github.com/Pithaya/spicetify-apps-dist/assets/73033465/9de2e12e-f289-4fc8-9068-1780d6ce5586)

**Comment by spliitbtw** [comment]
Same error here
![image](https://github.com/Pithaya/spicetify-apps-dist/assets/64521758/a1f6a38b-3522-4a71-813d-d139ba2a9f5b)
