### ISSUE TITLE
Jukebox says its not enabled

### ISSUE THREAD

**Issue by KawaiiiSheep** [Pithaya/spicetify-apps-dist#5]
Everything done right and icon is showing on the bottom of the page (the lil infinite symbol) and it is "on" but when i open the eternal jukebox page it says that its not loaded 
not sure what's really wrong with it lol 
![image](https://user-images.githubusercontent.com/34980384/222896014-5dbae846-1a42-41b9-afc3-c108ce745b46.png)
![image](https://user-images.githubusercontent.com/34980384/222896038-0892cc19-6866-4117-9c64-ee6c4f953d83.png)

**Comment by Pithaya** [comment]
Could be that there is no analysis available for the track, is it working for other songs or is it always disabled ?

**Comment by KawaiiiSheep** [comment]
> Could be that there is no analysis available for the track, is it working for other songs or is it always disabled ?

its constantly disabled 
cant even make the symbol light up. Will look with other songs tho

**Comment by Pithaya** [comment]
Is the issue still there with the lastest version ?

**Comment by Gimar250** [comment]
same problem here

**Comment by KawaiiiSheep** [comment]
> Is the issue still there with the lastest version ?

it seems that it was incompatible with one of the themes
all good now and works well 
icons are showing if on or off
