### ISSUE TITLE
artist names on flac files don't show properly (better local files)

### ISSUE THREAD

**Issue by KaleidoscopicPrism** [Pithaya/spicetify-apps-dist#54]
![image](https://github.com/Pithaya/spicetify-apps-dist/assets/66155989/fb0dcf0e-1fa1-425f-892a-a4588d4ae723)
![image](https://github.com/Pithaya/spicetify-apps-dist/assets/66155989/db406a3f-4045-4053-bb59-18a458f2f69a)
![image](https://github.com/Pithaya/spicetify-apps-dist/assets/66155989/47f6da19-deab-4477-afae-2043c1254938)

**Comment by KaleidoscopicPrism** [comment]
this doesn't show on any of my mp3 files btw

**Comment by rahaaatul** [comment]
I agree:
![image](https://github.com/Pithaya/spicetify-apps-dist/assets/86149861/22516f82-95ea-4c30-9772-8fbda9b098e8)

Also, lyrics plus froze playing this.
