### ISSUE TITLE
Jumps should only be going back in time, not forward

### ISSUE THREAD

**Issue by Joel05** [Pithaya/spicetify-apps-dist#7]
I've noticed the App jumping forwards in time. I think this doesnt really make sense, since in shortens the playtime, instead of making the song last longer/infinitely.

**Comment by Pithaya** [comment]
You can now check this option in the settings menu to disable jumps forward:

![image](https://user-images.githubusercontent.com/19533412/226173136-20bc4b94-9681-4f91-bea5-c6620a263e89.png)
