### ISSUE TITLE
help

### ISSUE THREAD

**Issue by JAMEIRds** [Pithaya/spicetify-apps-dist#9]
![image_2023-03-11_162222742](https://user-images.githubusercontent.com/127616791/224495721-7c4ac21b-1252-4e2d-be8a-80e24325fa4e.png)

**Comment by JordyThien** [comment]
@JAMEIRds Can you tell me what's in the "eternal-jukebox" folder? Did you download and copied the content of `eternal-jukebox` into `%appdata%\spicetify\CustomApps\eternal-jukebox`?
The content must come from the `eternal-jukebox` branch @ https://github.com/Pithaya/spicetify-apps-dist/tree/dist/eternal-jukebox

**Comment by Pithaya** [comment]
@JAMEIRds Please reopen the issue if you still need help
